steps:
- name: "gcr.io/cloud-builders/gcloud"
  dir: "backend"
  args: ["app", "deploy"]
  secretEnv:
  - 'FRONTEND_HOST'
  - 'MONGO_DB_NAME'
  - 'MONGO_HOST'
  - 'ORIGIN'
  - 'PRODUCTION'
  - 'SENDGRID_API_KEY'
  - 'SENDGRID_FROM_EMAIL'
  - 'USE_SENDGRID'
availableSecrets:
  secretManager:
  - versionName: projects/escapehatch/secrets/FRONTEND_HOST/versions/1
    env: 'FRONTEND_HOST'
  - versionName: projects/escapehatch/secrets/MONGO_DB_NAME/versions/1
    env: 'MONGO_DB_NAME'
  - versionName: projects/escapehatch/secrets/MONGO_HOST/versions/1
    env: 'MONGO_HOST'
  - versionName: projects/escapehatch/secrets/ORIGIN/versions/1
    env: 'ORIGIN'
  - versionName: projects/escapehatch/secrets/PRODUCTION/versions/1
    env: 'PRODUCTION'
  - versionName: projects/escapehatch/secrets/SENDGRID_API_KEY/versions/1
    env: 'SENDGRID_API_KEY'
  - versionName: projects/escapehatch/secrets/SENDGRID_FROM_EMAIL/versions/1
    env: 'SENDGRID_FROM_EMAIL'
  - versionName: projects/escapehatch/secrets/USE_SENDGRID/versions/1
    env: 'USE_SENDGRID'
