steps:
- name: "gcr.io/cloud-builders/gcloud"
  dir: "backend"
  args: ["app", "deploy"]
  secretEnv: ['MONGO_HOST', 'SENDGRID_API_KEY']
availableSecrets:
  secretManager:
  - versionName: projects/escapehatch/secrets/MONGO_HOST/versions/latest
    env: 'MONGO_HOST'
  - versionName: projects/escapehatch/secrets/SENDGRID_API_KEY/versions/latest
    env: 'SENDGRID_API_KEY'
options:
  logging: CLOUD_LOGGING_ONLY # Refs: https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts#running_builds_using_build_triggers
