runtime: go120
env_variables:
  # These are non-secret env vars. Put secret env vars in Google Secret Manager and add a loader for each var to main.go
  PROJECT_ID: escapehatch
  FRONTEND_HOST: 'https://www.escapehatch.ca'
  MONGO_DB_NAME: escapehatch
  ORIGIN: 'https://www.escapehatch.ca'
  PRODUCTION: 'true'
  SENDGRID_FROM_EMAIL: 'jake@jakestrang.com'
  USE_SENDGRID: 'true'
  USE_GCS: 'true'
  GCS_BUCKET_NAME: 'escapehatch.appspot.com'
  STATIC_URL_ROOT: 'https://storage.googleapis.com/escapehatch.appspot.com'
  USE_ATLAS: 'true'
