runtime: go120
env_variables:
  PROJECT_ID: escapehatch
  FRONTEND_HOST: 'https://www.escapehatch.ca'
  MONGO_DB_NAME: escapehatch
  ORIGIN: 'https://www.escapehatch.ca'
  PRODUCTION: true
  SENDGRID_FROM_EMAIL: 'jake@jakestrang.com'
  USE_SENDGRID: true
